import { NextRequest, NextResponse } from "next/server";
import Decimal from "decimal.js";
import { prisma } from "@/lib/prisma";
import { classify, confirmationsNeeded, observe } from "@/lib/crypto/verify";
import { rateLimit, requireCsrf } from "@/lib/server/security";

export async function POST(req:NextRequest,{params}:{params:Promise<{id:string}>}){
 const limited=rateLimit(req,12,60_000);if(limited)return limited;const csrf=requireCsrf(req);if(csrf)return csrf;const {id}=await params;
 const inv=await prisma.invoice.findUnique({where:{publicId:id}});if(!inv)return NextResponse.json({error:"Invoice not found"},{status:404});if(req.cookies.get("hh_session")?.value!==inv.buyerSession)return NextResponse.json({error:"Invoice not found"},{status:404});if(new Date()>inv.expiresAt){await prisma.invoice.update({where:{id:inv.id},data:{status:"EXPIRED",lastCheckedAt:new Date()}});return NextResponse.json({status:"EXPIRED"});}
 try{const observed=await observe(inv.currency,inv.walletAddress,inv.createdAt);const required=new Decimal(inv.cryptoAmount.toString());const candidates=observed.filter(p=>(!p.timestamp||p.timestamp>=new Date(inv.createdAt.getTime()-120_000))).sort((a,b)=>Math.abs(a.amount.minus(required).toNumber())-Math.abs(b.amount.minus(required).toNumber()));
 for(const p of candidates){const used=await prisma.payment.findUnique({where:{transactionHash:p.hash}});if(used&&used.invoiceId!==inv.id)continue;const needed=confirmationsNeeded(inv.currency);const status=classify(required,p.amount,p.confirmations,needed);await prisma.$transaction(async tx=>{await tx.payment.upsert({where:{transactionHash:p.hash},update:{confirmations:p.confirmations,amount:p.amount.toString(),raw:p.raw as any,confirmedAt:p.confirmations>=needed?new Date():null},create:{invoiceId:inv.id,transactionHash:p.hash,currency:inv.currency,amount:p.amount.toString(),confirmations:p.confirmations,raw:p.raw as any,confirmedAt:p.confirmations>=needed?new Date():null}});await tx.transaction.upsert({where:{transactionHash:p.hash},update:{confirmations:p.confirmations,amount:p.amount.toString(),raw:p.raw as any},create:{transactionHash:p.hash,currency:inv.currency,walletAddress:inv.walletAddress,amount:p.amount.toString(),confirmations:p.confirmations,raw:p.raw as any}});await tx.invoice.update({where:{id:inv.id},data:{status,transactionHash:p.hash,detectedAmount:p.amount.toString(),confirmations:p.confirmations,lastCheckedAt:new Date(),paidAt:["PAID","OVERPAID"].includes(status)?new Date():null}})});return NextResponse.json({status,transactionHash:p.hash,detectedAmount:p.amount.toString(),confirmations:p.confirmations})}
 await prisma.invoice.update({where:{id:inv.id},data:{lastCheckedAt:new Date()}});return NextResponse.json({status:"WAITING"});}catch(e:any){console.error("invoice_verify",e);return NextResponse.json({error:"Verification temporarily unavailable"},{status:502})}
}
